# Generated by Django 4.2.1 on 2023-10-05 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[("triagem", "Triagem"), ("cadastro", "Cadastro")],
                        max_length=20,
                    ),
                ),
                ("values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Msrs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_zendesk_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Cor"),
                            ("Preta", "Preta"),
                            ("Parda", "Parda"),
                            ("Indígena", "Indígena"),
                            ("Amarela", "Amarela"),
                            ("Branca", "Branca"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cis", "Eu sou uma mulher cis"),
                            ("trans", "Eu sou uma mulher trans/travesti"),
                            ("nda", "Não me identifico como mulher"),
                        ],
                        max_length=15,
                    ),
                ),
                ("whatsapp", models.CharField(max_length=11, verbose_name="Whatsapp")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Latitude"
                    ),
                ),
                (
                    "logintude",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Longitude"
                    ),
                ),
                ("pcd", models.BooleanField(default=False)),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Ensino fundamental incompleto",
                                "Ensino fundamental incompleto",
                            ),
                            (
                                "Ensino fundamental completo",
                                "Ensino fundamental completo",
                            ),
                            ("Ensino médio incompleto", "Ensino médio incompleto"),
                            ("Ensino médio completo", "Ensino médio completo"),
                            ("Ensino técnico", "Ensino técnico"),
                            (
                                "Ensino superior incompleto",
                                "Ensino superior incompleto",
                            ),
                            ("Ensino superior completo", "Ensino superior completo"),
                            ("Pós-graduação", "Pós-graduação"),
                            ("Mestrado", "Mestrado"),
                            ("Doutorado", "Doutorado"),
                            ("Pós-doutorado", "Pós-doutorado"),
                            ("Nunca frequentei/procurei", "Nunca frequentei/procurei"),
                        ],
                        max_length=40,
                        verbose_name="Nível de escolaridade",
                    ),
                ),
                (
                    "work_situation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Empregada com CLT", "Empregada com CLT"),
                            ("Empregada sem CLT", "Empregada sem CLT"),
                            ("Desempregada", "Desempregada"),
                            ("Empreendedora autônoma", "Empreendedora autônoma"),
                            (
                                "Estudante e com renda independente",
                                "Estudante e com renda independente",
                            ),
                            ("Aposentada", "Aposentada"),
                            (
                                "Estudante e dependente da minha família",
                                "Estudante e dependente da minha família",
                            ),
                        ],
                        max_length=40,
                        verbose_name="Situação de trabalho",
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Renda"
                    ),
                ),
                (
                    "violence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fui humilhada", "Fui humilhada"),
                            ("Levei um soco", "Levei um soco"),
                            ("Fui ameaçada", "Fui ameaçada"),
                            ("Levei um chute e/ou tapa", "Levei um chute e/ou tapa"),
                            (
                                "Sofri abusos e maus-tratos",
                                "Sofri abusos e maus-tratos",
                            ),
                            (
                                "Se/me negou a usar preservativo",
                                "Se/me negou a usar preservativo",
                            ),
                            (
                                "Fui perseguida e/ou vigiada",
                                "Fui perseguida e/ou vigiada",
                            ),
                            ("Me expôs na internet", "Me expôs na internet"),
                            (
                                "Fui forçada à alguma prática sexual",
                                "Fui forçada à alguma prática sexual",
                            ),
                            ("Fui empurrada", "Fui empurrada"),
                            (
                                "Não estou sofrendo nenhum tipo de violência",
                                "Não estou sofrendo nenhum tipo de violência",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Tipo de violência",
                    ),
                ),
                (
                    "duration_of_violence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mais de 10 anos", "Mais de 10 anos"),
                            ("Entre 2 anos e 10 anos", "Entre 2 anos e 10 anos"),
                            ("Entre 1 e 2 anos", "Entre 1 e 2 anos"),
                            ("Entre 6 meses e 1 ano", "Entre 6 meses e 1 ano"),
                            ("Entre 3 e 6 meses", "Entre 3 e 6 meses"),
                            ("Menos de 3 meses", "Menos de 3 meses"),
                            ("Menos de 1 semana", "Menos de 1 semana"),
                            ("Nos últimos 3 dias", "Nos últimos 3 dias"),
                        ],
                        max_length=30,
                        verbose_name="Duração da violência",
                    ),
                ),
                (
                    "author_of_violence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pai", "Pai"),
                            ("Mãe", "Mãe"),
                            ("Irmão/Irmã", "Irmão/Irmã"),
                            ("Tio/Tia", "Tio/Tia"),
                            ("Primo/Prima", "Primo/Prima"),
                            ("Vizinho/Vizinha", "Vizinho/Vizinha"),
                            ("Namorado/Namorada", "Namorado/Namorada"),
                            ("Marido/Esposa", "Marido/Esposa"),
                            ("Ex-namorado/Ex-namorada", "Ex-namorado/Ex-namorada"),
                            ("Ex-marido/Ex-esposa", "Ex-marido/Ex-esposa"),
                            ("Amigo/Amiga", "Amigo/Amiga"),
                            ("Filho/Filha", "Filho/Filha"),
                        ],
                        max_length=30,
                        verbose_name="Autor da violência",
                    ),
                ),
                ("story", models.TextField(verbose_name="Relato")),
                (
                    "risk_factors",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "O(A) autor(a) da violência possui acesso à arma de fogo",
                                "O(A) autor(a) da violência possui acesso à arma de fogo",
                            ),
                            ("Estou em cárcere privado", "Estou em cárcere privado"),
                            (
                                "A violência ocorreu em ambiente doméstico",
                                "A violência ocorreu em ambiente doméstico",
                            ),
                            (
                                "A violência ocorreu durante a gestação",
                                "A violência ocorreu durante a gestação",
                            ),
                            (
                                "Eu não me sinto segura em casa",
                                "Eu não me sinto segura em casa",
                            ),
                            (
                                "O(A) autor(a) da violência tem diagnóstico de doença psiquiátrica",
                                "O(A) autor(a) da violência tem diagnóstico de doença psiquiátrica",
                            ),
                            (
                                "O(A) autor(a) da violência faz uso de substância psicoativa ",
                                "O(A) autor(a) da violência faz uso de substância psicoativa ",
                            ),
                            (
                                "Dependo financeiramente do(a) autor(a) da violência",
                                "Dependo financeiramente do(a) autor(a) da violência",
                            ),
                            (
                                "A violência ocorreu em ambiente de trabalho",
                                "A violência ocorreu em ambiente de trabalho",
                            ),
                            (
                                "A violência ocorreu em ambiente público (internet, rua, etc)",
                                "A violência ocorreu em ambiente público (internet, rua, etc)",
                            ),
                            (
                                "Tive acesso negado aos serviços públicos de atendimento à mulher",
                                "Tive acesso negado aos serviços públicos de atendimento à mulher",
                            ),
                            (
                                "As agressões ou ameaças do(a) autor(a) da violência contra mim se tornaram mais frequentes ou mais graves nos últimos meses",
                                "As agressões ou ameaças do(a) autor(a) da violência contra mim se tornaram mais frequentes ou mais graves nos últimos meses",
                            ),
                        ],
                        max_length=140,
                        verbose_name="Fatores de Risco",
                    ),
                ),
                (
                    "protective_factors",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Eu possuo rede de apoio (familiares, amigos, vizinhos etc)",
                                "Eu possuo rede de apoio (familiares, amigos, vizinhos etc)",
                            ),
                            (
                                "Não resido com o(a) autor(a) da violência",
                                "Não resido com o(a) autor(a) da violência",
                            ),
                            ("Me sinto segura em casa", "Me sinto segura em casa"),
                            (
                                "Não dependo financeiramente do(a) autor(a) da violência",
                                "Não dependo financeiramente do(a) autor(a) da violência",
                            ),
                            (
                                "O local onde resido possui serviços públicos de atendimento à mulher com atendimento qualificado",
                                "O local onde resido possui serviços públicos de atendimento à mulher com atendimento qualificado",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Fatores de proteção",
                    ),
                ),
                (
                    "public_service",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "CREAS",
                                "Centro de Referência Especializado de Assistência Social (CREAS)",
                            ),
                            (
                                "CRAS",
                                "Centro de Referência de Assistência Social (CRAS)",
                            ),
                            ("UBS", "Unidade Básica de Saúde (UBS) "),
                            (
                                "CRM/CDCM/CRAM/CIAM ",
                                "Centro de Referência da Mulher (CRM); Centro de Defesa e de Convivência da Mulher (CDCM); Centro de Referência de Atendimento à Mulher (CRAM); Centro Integrado de Atendimento à Mulher (CIAM) ",
                            ),
                            ("CMB", "Casa da Mulher Brasileira (CMB)"),
                            ("DEAM", "Delegacia Especializada da Mulher (DEAM)"),
                            ("Delegacia Civil", "Delegacia Civil"),
                            (
                                "Hospital de Abortamento Legal ",
                                "Hospital de Abortamento Legal ",
                            ),
                            ("MP", "Ministério Público (MP)"),
                            ("CAPS", "Centro de Atenção Psicossocial (CAPS)"),
                            (
                                "Estou sendo atendida por um coletivo/movimento",
                                "Estou sendo atendida por um coletivo/movimento",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Serviços públicos",
                    ),
                ),
                (
                    "type_of_support",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("psicologico", "Psicológico"),
                            ("juridico", "Jurídico"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de acolhimento",
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Instagram", "Instagram"),
                            ("Facebook", "Facebook"),
                            ("Twitter", "Twitter"),
                            ("Podcast", "Podcast"),
                            ("Reportagem/notícia", "Reportagem/notícia"),
                            ("Indicação", "Indicação"),
                            ("Outros", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Como teve acesso ao Mapa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Inscrita", "Inscrita"),
                            ("Incompleta", "Incompleta"),
                        ],
                        max_length=15,
                        verbose_name="Status da inscrição",
                    ),
                ),
                (
                    "support_on_queue",
                    models.BooleanField(
                        default=False, verbose_name="Tipos de acolhimento na fila"
                    ),
                ),
                (
                    "on_queue",
                    models.BooleanField(
                        default=False, verbose_name="Fila para o match"
                    ),
                ),
                (
                    "online",
                    models.BooleanField(
                        default=False, verbose_name="Aceita atendimento online"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("verde", "verde"),
                            ("vermelho", "vermelho"),
                            ("amarelo", "amarelo"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Data da inscrição"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_date"),
                ),
                (
                    "match",
                    models.BooleanField(default=False, verbose_name="Vai pro match"),
                ),
            ],
        ),
    ]
