# Generated by Django 4.2.1 on 2023-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrs', '0002_city_remove_msrs_violence_msrs_digital_violence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
