# Generated by Django 4.2.1 on 2023-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msrs", "0002_remove_msrs_violence_msrs_digital_violence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrs",
            name="author_of_violence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Quem é ou foi o(a) autor(a) da violência?"),
                    ("Pai", "Pai"),
                    ("Mãe", "Mãe"),
                    ("Irmão/Irmã", "Irmão/Irmã"),
                    ("Tio/Tia", "Tio/Tia"),
                    ("Primo/Prima", "Primo/Prima"),
                    ("Vizinho/Vizinha", "Vizinho/Vizinha"),
                    ("Namorado/Namorada", "Namorado/Namorada"),
                    ("Marido/Esposa", "Marido/Esposa"),
                    ("Ex-namorado/Ex-namorada", "Ex-namorado/Ex-namorada"),
                    ("Ex-marido/Ex-esposa", "Ex-marido/Ex-esposa"),
                    ("Amigo/Amiga", "Amigo/Amiga"),
                    ("Filho/Filha", "Filho/Filha"),
                ],
                max_length=30,
                verbose_name="Autor da violência",
            ),
        ),
        migrations.AlterField(
            model_name="msrs",
            name="duration_of_violence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Há quanto tempo está sofrendo violência?"),
                    ("Mais de 10 anos", "Mais de 10 anos"),
                    ("Entre 2 anos e 10 anos", "Entre 2 anos e 10 anos"),
                    ("Entre 1 e 2 anos", "Entre 1 e 2 anos"),
                    ("Entre 6 meses e 1 ano", "Entre 6 meses e 1 ano"),
                    ("Entre 3 e 6 meses", "Entre 3 e 6 meses"),
                    ("Menos de 3 meses", "Menos de 3 meses"),
                    ("Menos de 1 semana", "Menos de 1 semana"),
                    ("Nos últimos 3 dias", "Nos últimos 3 dias"),
                ],
                max_length=30,
                verbose_name="Duração da violência",
            ),
        ),
    ]
