# Generated by Django 4.2.1 on 2023-11-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0021_alter_integrationlogs_error"),
        ("msrs", "0003_alter_msrs_author_of_violence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrs",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="volunteers.cities",
                verbose_name="Cidade",
            ),
        ),
    ]
