# Generated by Django 4.2.1 on 2023-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrs', '0003_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
