# Generated by Django 4.2.1 on 2023-11-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msrs', '0003_place_alter_msrs_author_of_violence_alter_msrs_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
