# Generated by Django 4.2.1 on 2023-12-14 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msrs", "0004_alter_msrs_city"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="msrs",
            table="msrs",
        ),
    ]
