# Generated by Django 4.2.1 on 2023-05-29 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_ocuppation_formdata_type_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdata",
            name="created_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="formdata",
            name="total_steps",
            field=models.IntegerField(default=1),
        ),
    ]
