# Generated by Django 4.2.1 on 2023-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_formdata_created_date_formdata_total_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdata",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_date"),
        ),
    ]
