# Generated by Django 4.2.1 on 2023-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="step",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
