# Generated by Django 4.2.1 on 2023-05-22 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteers", "0002_alter_volunteer_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ocuppation",
                    models.CharField(
                        blank=True,
                        choices=[("psicologa", "Psicóloga"), ("advogada", "Advogada")],
                        max_length=10,
                    ),
                ),
                ("step", models.IntegerField(default=1)),
                ("values", models.JSONField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Volunteer",
        ),
    ]
