# Generated by Django 4.2.1 on 2023-05-25 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteers", "0003_formdata_delete_volunteer"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdata",
            name="total_steps",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="formdata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formdata",
            name="values",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
