# Generated by Django 4.2.1 on 2023-05-29 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0004_formdata_total_steps_alter_formdata_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formdata",
            old_name="ocuppation",
            new_name="type_form",
        ),
        migrations.RemoveField(
            model_name="formdata",
            name="total_steps",
        ),
    ]
