# Generated by Django 4.2.1 on 2023-05-29 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0007_formdata_updated_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formdata",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="formdata",
            old_name="updated_date",
            new_name="updated_at",
        ),
    ]
