# Generated by Django 4.2.1 on 2023-07-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0009_integrationlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationlogs",
            name="external_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
