# Generated by Django 4.2.1 on 2023-07-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0010_integrationlogs_external_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationlogs",
            name="integration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bonde", "Bonde"),
                    ("moodle", "Moodle"),
                    ("action_network", "Action Network"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="integrationlogs",
            name="status",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="integrationlogs",
            name="type",
            field=models.CharField(max_length=30),
        ),
    ]
