# Generated by Django 4.2.1 on 2023-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0012_volunteer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="logintude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
