# Generated by Django 4.2.1 on 2023-10-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0013_alter_volunteer_latitude_alter_volunteer_logintude"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="ocuppation",
            field=models.CharField(
                blank=True,
                choices=[("psicologa", "Psicóloga"), ("advogada", "Advogada")],
                max_length=10,
            ),
        ),
    ]
