# Generated by Django 4.2.1 on 2023-11-21 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0014_volunteer_ocuppation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                ("city_id", models.IntegerField(primary_key=True, serialize=False)),
                ("city_value", models.CharField(max_length=100)),
                ("city_label", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("ibge_code", models.IntegerField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_date"),
                ),
            ],
            options={
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="VolunteerAvailability",
            fields=[
                (
                    "volunteer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="volunteer_availability",
                        serialize=False,
                        to="volunteers.volunteer",
                    ),
                ),
                ("current_matches", models.IntegerField(default=0)),
                ("max_matches", models.IntegerField(default=1)),
                ("is_available", models.BooleanField()),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("PSYCOLOGICAL", "Psicológico"),
                            ("LEGAL", "Jurídico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("support_expertise", models.CharField(choices=[], max_length=100)),
                ("offers_online_support", models.BooleanField()),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_date"),
                ),
            ],
            options={
                "db_table": "volunteer_availability",
            },
        ),
        migrations.AlterModelTable(
            name="volunteer",
            table="volunteers",
        ),
        migrations.CreateModel(
            name="VolunteerStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volunteer_status",
                    models.CharField(
                        choices=[
                            ("cadastrada", "cadastrada"),
                            ("reprovada_diretrizes", "reprovada_diretrizes"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteers.volunteer",
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_status_history",
            },
        ),
    ]
