# Generated by Django 4.2.1 on 2023-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "volunteers",
            "0015_cities_volunteeravailability_alter_volunteer_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cities",
            name="city_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
