# Generated by Django 4.2.1 on 2023-11-20 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0015_volunteers_availability_and_status_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                ("city_id", models.IntegerField(primary_key=True, serialize=False)),
                ("city_value", models.CharField(max_length=100)),
                ("city_label", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("ibge_code", models.IntegerField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_date"),
                ),
            ],
            options={
                "db_table": "cities",
            },
        ),
    ]
