# Generated by Django 4.2.1 on 2023-11-10 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0016_remove_integrationlogs_external_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="volunteer",
            old_name="volunteer_status",
            new_name="condition",
        ),
    ]
