# Generated by Django 4.2.1 on 2023-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0017_rename_volunteer_status_volunteer_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="moodle_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
