# Generated by Django 4.2.1 on 2023-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0017_alter_cities_created_at_alter_cities_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteeravailability",
            name="state",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
