# Generated by Django 4.2.1 on 2023-11-21 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0017_alter_cities_created_at_alter_cities_updated_at_and_more"),
        ("volunteers", "0018_volunteer_moodle_id"),
    ]

    operations = []
