# Generated by Django 4.2.1 on 2023-11-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0019_alter_volunteeravailability_state'),
        ('volunteers', '0019_merge_20231121_2008'),
    ]

    operations = [
    ]
