# Generated by Django 4.2.1 on 2023-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0020_merge_20231122_1932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationlogs",
            name="error",
            field=models.TextField(),
        ),
    ]
