# Generated by Django 4.2.1 on 2023-11-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0021_alter_integrationlogs_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="form_entries_id",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteer",
            name="zendesk_user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
