# Generated by Django 4.2.1 on 2023-11-24 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0022_rename_logintude_volunteer_longitude_and_more"),
        ("volunteers", "0022_volunteer_form_entries_id_volunteer_zendesk_user_id"),
    ]

    operations = []
