# Generated by Django 4.2.1 on 2023-11-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0023_merge_20231124_1947"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerstatushistory",
            name="volunteer_status",
        ),
        migrations.AddField(
            model_name="volunteerstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Aprovada"),
                    ("available", "Disponível"),
                    ("training", "Capacitação"),
                    ("totally_booked", "Atingiu máximo de atendimentos"),
                    ("unavailable_vacation", "Indisponível - Férias"),
                    ("unavailable_maternity", "Indisponível - Maternidade"),
                    ("unavailable_health", "Indisponível - Saúde"),
                    ("unavailable_work_study", "Indisponível - Trabalho e Estudo"),
                    ("unavailable_other", "Indisponível - Outros Motivos"),
                    ("unavailable_schedule", "Indisponível - Agenda"),
                    ("unavailable_no_answer", "Indisponível - Sem Resposta"),
                    ("incomplete_data_address", "Dados incompletos - Endereço"),
                    ("incomplete_data_phone", "Dados incompletos - Telefone"),
                    ("incomplete_data_email", "Dados incompletos - Email"),
                    ("rejected_case_study", "Reprovada - Estudo de Caso"),
                    ("rejected_guidelines", "Reprovada - Diretrizes do Mapa"),
                    ("rejected_invalid_register", "Reprovada - Registro inválido"),
                    ("rejected_unethical", "Anti-ética"),
                    ("unsubscribed", "Descadastrada"),
                ],
                default="not_found",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Identidade de gênero"),
                    ("cis_woman", "Mulher cisgênero"),
                    ("trans_woman", "Mulher transgênero/travesti"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered", "Aprovada"),
                    ("available", "Disponível"),
                    ("training", "Capacitação"),
                    ("totally_booked", "Atingiu máximo de atendimentos"),
                    ("unavailable_vacation", "Indisponível - Férias"),
                    ("unavailable_maternity", "Indisponível - Maternidade"),
                    ("unavailable_health", "Indisponível - Saúde"),
                    ("unavailable_work_study", "Indisponível - Trabalho e Estudo"),
                    ("unavailable_other", "Indisponível - Outros Motivos"),
                    ("unavailable_schedule", "Indisponível - Agenda"),
                    ("unavailable_no_answer", "Indisponível - Sem Resposta"),
                    ("incomplete_data_address", "Dados incompletos - Endereço"),
                    ("incomplete_data_phone", "Dados incompletos - Telefone"),
                    ("incomplete_data_email", "Dados incompletos - Email"),
                    ("rejected_case_study", "Reprovada - Estudo de Caso"),
                    ("rejected_guidelines", "Reprovada - Diretrizes do Mapa"),
                    ("rejected_invalid_register", "Reprovada - Registro inválido"),
                    ("rejected_unethical", "Anti-ética"),
                    ("unsubscribed", "Descadastrada"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="form_entries_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Cor"),
                    ("black", "Preta"),
                    ("brown", "Parda"),
                    ("indigenous", "Indígena"),
                    ("yellow", "Amarela"),
                    ("white", "Branca"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="ocuppation",
            field=models.CharField(
                blank=True,
                choices=[("psychologist", "Psicóloga"), ("lawyer", "Advogada")],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="offers_libras_support",
            field=models.BooleanField(default=False, verbose_name="Libras"),
        ),
        migrations.AlterField(
            model_name="volunteeravailability",
            name="support_expertise",
            field=models.CharField(
                choices=[
                    ("Violência de Gênero", "Violência de Gênero"),
                    ("Família", "Família"),
                    ("Penal", "\tPenal"),
                    ("Trabalhista", "Trabalhista"),
                    ("Cível", "Cível"),
                    ("Administrativo", "Administrativo"),
                    ("Empresarial", "Empresarial"),
                    ("Tributário", "Tributário"),
                    ("Digital", "\tDigital"),
                    ("Ambiental\t", "Ambiental"),
                    ("Outros", "Outros"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="volunteeravailability",
            name="support_type",
            field=models.CharField(
                choices=[("psychological", "Psicológico"), ("legal", "Jurídico")],
                max_length=20,
            ),
        ),
    ]
