# Generated by Django 4.2.1 on 2023-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0026_alter_volunteer_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="state",
            field=models.CharField(max_length=9, verbose_name="Estado"),
        ),
    ]
