# Generated by Django 4.2.1 on 2023-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0028_alter_volunteer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteeravailability",
            name="state",
            field=models.CharField(max_length=9),
        ),
    ]
