# Generated by Django 4.2.1 on 2023-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0031_alter_volunteer_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="street",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rua"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="state",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Estado"
            ),
        ),
    ]
