# Generated by Django 4.2.1 on 2023-12-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0034_alter_volunteeravailability_support_expertise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="availability",
            field=models.IntegerField(
                blank=True,
                choices=[("", "Vagas para atendimento"), (1, "1"), (2, "2"), (3, "3")],
            ),
        ),
    ]
