# Generated by Django 4.2.1 on 2023-12-19 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0035_alter_volunteer_availability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="whatsapp",
        ),
    ]
